'use strict';
document.addEventListener('DOMContentLoaded',()=>{
  const BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
  const KEY='adq_civis_lancamentos_v14',CFG_KEY='adq_civis_cfg_v14_6',OF_KEY='adq_civis_ofs_v11',SUP_KEY='adq_civis_suppliers_v14';
  const DEFAULT_CFG={prof:0,ajud:0,almoco:0,almoco_mode:'por_pessoa',mult_sab:1.5,mult_dom:2.0};
  const parse=(s,f)=>{try{return s?JSON.parse(s):structuredClone(f)}catch{return structuredClone(f)}};
  let cfg={...DEFAULT_CFG,...parse(localStorage.getItem(CFG_KEY),{})};
  let lanc=parse(localStorage.getItem(KEY),[]),ofs=parse(localStorage.getItem(OF_KEY),[]),sups=parse(localStorage.getItem(SUP_KEY),[]);
  if(!Array.isArray(lanc))lanc=[];if(!Array.isArray(ofs))ofs=[];if(!Array.isArray(sups))sups=[];
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
  const n=v=>{if(v==null)return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;const s=String(v).replace(/\uFEFF/g,'').replace(/R\$\s?/gi,'').replace(/\s+/g,'');if(!s)return 0;const norm=s.includes(',')?s.replace(/\./g,'').replace(',','.') : s;const x=parseFloat(norm);return Number.isFinite(x)?x:0};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const toast=m=>{const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)};
  const normalize=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
  const persist=()=>{localStorage.setItem(KEY,JSON.stringify(lanc));localStorage.setItem(CFG_KEY,JSON.stringify(cfg));localStorage.setItem(OF_KEY,JSON.stringify(ofs));localStorage.setItem(SUP_KEY,JSON.stringify(sups))};
  const canonicalSupplierName=input=>{const clean=normalize(input);if(!clean)return String(input||'').trim();for(const s of sups){if(normalize(s.name)===clean||(s.aliases||[]).some(a=>normalize(a)===clean))return s.name}return String(input||'').trim()};
  const fatorDia=t=>t==='sabado'?(+cfg.mult_sab||1.5):t==='domingo'?(+cfg.mult_dom||2):1;
  const almocoTotal=l=>{const ppl=(+l.profissionais||0)+(+l.ajudantes||0),v=+l.almoco||0,mode=cfg.almoco_mode||'por_pessoa';if(mode==='valor')return v;if(mode==='qtd')return v*ppl*(+cfg.almoco||0);return ppl*(+cfg.almoco||0)};
  const gasto=l=>(+l.materiais||0)+(+l.profissionais||0)*(+cfg.prof||0)*fatorDia(l.tipo_dia||'util')+(+l.ajudantes||0)*(+cfg.ajud||0)*fatorDia(l.tipo_dia||'util')+almocoTotal(l)+(+l.translado||0);
  const sum=(arr,fn)=>arr.reduce((a,x)=>a+(+fn(x)||0),0);
  const fmtDate=iso=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(iso||'');return m?`${m[3]}/${m[2]}/${m[1]}`:(iso||'')};

  function moneyFields(){
    $$('.money').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';el.addEventListener('focus',()=>{if(n(el.value)===0)el.value=''});el.addEventListener('blur',()=>{el.value=n(el.value).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})})});
  }
  function setMoney(id,value){const e=$(id);if(e)e.value=n(value).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}

  function activate(id){$$('.tab').forEach(t=>t.classList.toggle('active',t.id===id));$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));if(id==='dashboard')renderAll();if(id==='ofs')renderOFs();if(id==='fornecedores')renderSuppliers();if(id==='config')renderConfig();if(id==='lancamentos'){fillOFs(true);renderDatalist();moneyFields()}}
  $$('[data-tab]').forEach(b=>b.onclick=()=>activate(b.dataset.tab));

  function fillOFs(preserve=true){const a=$('#ofId'),b=$('#selOF');const build=all=>(all?'<option value="__ALL__">— Todas OFs —</option>':'')+ofs.map(o=>`<option value="${esc(o.id)}">${esc(o.id)} — ${esc(o.cliente||'')}</option>`).join('');if(a){const cur=preserve?a.value:'';a.innerHTML=build(false);if(cur&&[...a.options].some(o=>o.value===cur))a.value=cur}if(b){const cur=preserve?b.value:'';b.innerHTML=build(true);if(cur&&[...b.options].some(o=>o.value===cur))b.value=cur;else b.value='__ALL__'}}
  function renderDatalist(){const d=$('#fornList');if(d)d.innerHTML=sups.map(s=>`<option value="${esc(s.name)}"></option>`).join('')}

  function filtered(){const of=$('#selOF')?.value||'__ALL__',de=$('#fDe')?.value||'',ate=$('#fAte')?.value||'',forn=normalize($('#fFornecedor')?.value||'');return lanc.filter(l=>(of==='__ALL__'||l.of_id===of)&&(!de||l.data>=de)&&(!ate||l.data<=ate)&&(!forn||normalize(canonicalSupplierName(l.fornecedor||'')).includes(forn))).sort((a,b)=>(a.data||'').localeCompare(b.data||''))}
  let charts=[];
  function renderCharts(rows){charts.forEach(c=>c?.destroy?.());charts=[];if(!window.Chart)return;const byDate={};rows.forEach(r=>{const k=r.data||'—';byDate[k]=(byDate[k]||0)+gasto(r)});const dates=Object.keys(byDate).sort();const categories={Materiais:sum(rows,r=>r.materiais), 'Mão de Obra':sum(rows,r=>(r.profissionais*(+cfg.prof||0)+r.ajudantes*(+cfg.ajud||0))*fatorDia(r.tipo_dia||'util')),Indiretos:sum(rows,r=>almocoTotal(r)+(+r.translado||0))};const byF={};rows.forEach(r=>{const v=+r.materiais||0,k=canonicalSupplierName(r.fornecedor||'');if(k&&v>0)byF[k]=(byF[k]||0)+v});const common={responsive:true,maintainAspectRatio:false};const c1=$('#graficoEvolucao'),c2=$('#graficoCategorias'),c3=$('#graficoFornecedores');if(c1)charts.push(new Chart(c1,{type:'line',data:{labels:dates.map(fmtDate),datasets:[{label:'Total por dia',data:dates.map(d=>byDate[d]),tension:.25}]},options:{...common,plugins:{legend:{display:false}}}}));if(c2)charts.push(new Chart(c2,{type:'doughnut',data:{labels:Object.keys(categories),datasets:[{data:Object.values(categories)}]},options:{...common,plugins:{legend:{position:'bottom'}}}}));if(c3)charts.push(new Chart(c3,{type:'bar',data:{labels:Object.keys(byF),datasets:[{label:'Materiais por fornecedor',data:Object.values(byF)}]},options:{...common,plugins:{legend:{display:false}}}}))}
  function renderKpis(rows){const mat=sum(rows,r=>r.materiais),mo=sum(rows,r=>(r.profissionais*(+cfg.prof||0)+r.ajudantes*(+cfg.ajud||0))*fatorDia(r.tipo_dia||'util')),alm=sum(rows,almocoTotal),tra=sum(rows,r=>r.translado),ind=alm+tra,total=mat+mo+ind;$('#kpiMateriais').textContent=BRL.format(mat);$('#kpiMO').textContent=BRL.format(mo);$('#kpiIndiretos').textContent=BRL.format(ind);$('#kpiTotal').textContent=BRL.format(total);$('#kpiRegistros').textContent=rows.length?`${rows.length} registros`:'Sem registros';$('#kpiHh').textContent=`${sum(rows,r=>(+r.profissionais||0)+(+r.ajudantes||0))} pessoas·dia`;$('#kpiIndPct').textContent=`Indiretos ${total?(ind/total*100).toFixed(1):0}%`;$('#kpiAlmoco').textContent=BRL.format(alm);$('#kpiTranslado').textContent=BRL.format(tra);$('#kpiAlmocoSub').textContent=rows.length?`média ${BRL.format(alm/rows.length)}`:'—';$('#kpiTransladoSub').textContent=rows.length?`média ${BRL.format(tra/rows.length)}`:'—';const sel=$('#selOF')?.value||'__ALL__';let orcado=0,gastoOF=0;if(sel==='__ALL__'){orcado=sum(ofs,o=>o.orcado);gastoOF=sum(lanc,gasto)}else{const o=ofs.find(x=>x.id===sel);orcado=+o?.orcado||0;gastoOF=sum(lanc.filter(x=>x.of_id===sel),gasto)}const saldo=orcado-gastoOF;$('#pillOrcado').textContent=`Orçado: ${orcado?BRL.format(orcado):'—'}`;$('#pillSaldo').textContent=`Saldo: ${BRL.format(saldo)}`;$('#pillSaldo').classList.remove('tag-warn','tag-danger');if(orcado>0){const p=gastoOF/orcado;if(saldo<0)$('#pillSaldo').classList.add('tag-danger');else if(p>=.8)$('#pillSaldo').classList.add('tag-warn')}}
  function renderTable(rows){const tb=$('#tabela tbody');tb.innerHTML=rows.map(l=>{const ppl=(+l.profissionais||0)+(+l.ajudantes||0),a=almocoTotal(l),info=cfg.almoco_mode==='qtd'?`${n(l.almoco)} × ${ppl} × ${BRL.format(+cfg.almoco||0)} = ${BRL.format(a)}`:BRL.format(a);return `<tr data-id="${esc(l.id)}"><td>${esc(l.of_id||'')}</td><td>${esc(fmtDate(l.data))}</td><td>${esc(canonicalSupplierName(l.fornecedor||''))}</td><td>${BRL.format(+l.materiais||0)}</td><td>${+l.profissionais||0}</td><td>${+l.ajudantes||0}</td><td>${info}</td><td>${BRL.format(+l.translado||0)}</td><td><b>${BRL.format(gasto(l))}</b></td><td><div class="btns"><button class="btn edit">Editar</button><button class="btn ghost danger del">Excluir</button></div></td></tr>`}).join('');tb.querySelectorAll('tr').forEach(tr=>{const item=lanc.find(x=>x.id===tr.dataset.id);tr.querySelector('.edit').onclick=()=>enterEdit(item);tr.querySelector('.del').onclick=()=>{if(confirm('Remover este lançamento?')){lanc=lanc.filter(x=>x.id!==item.id);persist();renderAll()}}})}
  function renderAll(){fillOFs(true);renderDatalist();const rows=filtered();renderKpis(rows);renderCharts(rows);renderTable(rows);renderSuppliers()}

  let editId=null;
  function enterEdit(l){if(!l)return;editId=l.id;activate('lancamentos');$('#formTitle').textContent='Editar Lançamento';$('#btnSalvarLanc').textContent='Salvar';$('#btnCancelarEdit').hidden=false;$('#ofId').value=l.of_id||'';$('#data').value=l.data||'';$('#fornecedor').value=l.fornecedor||'';setMoney('#materiais',l.materiais);$('#profissionais').value=l.profissionais||0;$('#ajudantes').value=l.ajudantes||0;setMoney('#almoco',l.almoco);setMoney('#translado',l.translado);$('#tipoDia').value=l.tipo_dia||'util'}
  function clearForm(keepOF=true){const of=$('#ofId').value;editId=null;$('#formTitle').textContent='Novo Lançamento';$('#btnSalvarLanc').textContent='Adicionar';$('#btnCancelarEdit').hidden=true;$('#data').value='';$('#fornecedor').value='';setMoney('#materiais',0);$('#profissionais').value=0;$('#ajudantes').value=0;setMoney('#almoco',0);setMoney('#translado',0);$('#tipoDia').value='util';if(keepOF)$('#ofId').value=of}
  $('#btnCancelarEdit').onclick=()=>clearForm();
  $('#form').onsubmit=e=>{e.preventDefault();const of_id=$('#ofId').value;if(!of_id)return alert('Cadastre e selecione uma OF.');const data={of_id,data:$('#data').value,fornecedor:canonicalSupplierName($('#fornecedor').value),materiais:n($('#materiais').value),profissionais:parseInt($('#profissionais').value)||0,ajudantes:parseInt($('#ajudantes').value)||0,almoco:n($('#almoco').value),translado:n($('#translado').value),tipo_dia:$('#tipoDia').value||'util'};const wasEditing=!!editId;if(editId){const i=lanc.findIndex(x=>x.id===editId);if(i>=0)lanc[i]={...lanc[i],...data}}else lanc.push({id:uid(),...data});persist();clearForm();renderAll();toast(wasEditing?'Lançamento atualizado':'Lançamento salvo')};

  function renderOFs(){const wrap=$('#ofCards');const spent={};lanc.forEach(l=>spent[l.of_id]=(spent[l.of_id]||0)+gasto(l));wrap.innerHTML=ofs.length?ofs.map(o=>{const g=spent[o.id]||0,orc=+o.orcado||0,saldo=orc-g,pct=orc>0?Math.min(100,g/orc*100):0;return `<div class="of-card card"><div class="head"><div><b>${esc(o.id)}</b><div class="muted">${esc(o.cliente||'')}</div></div><span class="pill">Orçado: ${orc?BRL.format(orc):'—'}</span></div><div class="muted" style="margin-top:8px">${esc(o.desc||'Sem descrição')}</div><div class="btns" style="margin-top:10px"><span class="pill">Gasto: <b>${BRL.format(g)}</b></span><span class="pill ${saldo<0?'tag-danger':pct>=80?'tag-warn':''}">Saldo: <b>${BRL.format(saldo)}</b></span></div><div class="of-progress"><div class="of-bar" style="width:${pct}%"></div></div></div>`}).join(''):'<div class="empty">Nenhuma OF cadastrada neste navegador.</div>';fillOFs(true)}
  $('#formOF').onsubmit=e=>{e.preventDefault();const id=$('#ofNumero').value.trim();if(!id)return;if(ofs.some(o=>o.id===id))return alert('Já existe uma OF com esse ID.');ofs.push({id,cliente:$('#ofCliente').value.trim(),orcado:n($('#ofOrcado').value),desc:$('#ofDesc').value.trim()});persist();e.target.reset();moneyFields();renderOFs();renderAll();toast('OF cadastrada')};
  $('#btnResetOFs').onclick=()=>{if(confirm('Excluir TODAS as OFs? Os lançamentos ficarão sem OF.')){ofs=[];lanc=lanc.map(l=>({...l,of_id:''}));persist();renderOFs();renderAll()}};

  function renderSuppliers(){renderDatalist();const wrap=$('#supList');if(!wrap)return;wrap.innerHTML=sups.length?sups.map(s=>`<div class="sup-item" data-id="${esc(s.id)}"><div><b>${esc(s.name)}</b><small>${esc((s.aliases||[]).join(', ')||'Sem apelidos')}</small></div><div class="btns"><button class="btn edit">Editar</button><button class="btn ghost danger del">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum fornecedor cadastrado.</div>';wrap.querySelectorAll('.sup-item').forEach(r=>{const s=sups.find(x=>x.id===r.dataset.id);r.querySelector('.edit').onclick=()=>{$('#supNome').value=s.name;$('#supAliases').value=(s.aliases||[]).join(', ');sups=sups.filter(x=>x.id!==s.id);persist();renderSuppliers()};r.querySelector('.del').onclick=()=>{if(confirm(`Excluir ${s.name}?`)){sups=sups.filter(x=>x.id!==s.id);persist();renderSuppliers();renderAll()}}})}
  $('#btnAddSup').onclick=()=>{const name=$('#supNome').value.trim();if(!name)return alert('Informe o nome.');if(sups.some(x=>normalize(x.name)===normalize(name)))return alert('Fornecedor já cadastrado.');sups.push({id:uid(),name,aliases:$('#supAliases').value.split(',').map(x=>x.trim()).filter(Boolean)});$('#supNome').value='';$('#supAliases').value='';persist();renderSuppliers();toast('Fornecedor salvo')};
  $('#btnUnificar').onclick=()=>{lanc=lanc.map(l=>({...l,fornecedor:canonicalSupplierName(l.fornecedor||'')}));persist();renderAll();toast('Fornecedores unificados')};

  function renderConfig(){setMoney('#cfgProf',cfg.prof);setMoney('#cfgAjud',cfg.ajud);setMoney('#cfgAlmoco',cfg.almoco);$('#cfgAlmocoMode').value=cfg.almoco_mode||'por_pessoa';$('#cfgMultSab').value=cfg.mult_sab??1.5;$('#cfgMultDom').value=cfg.mult_dom??2;moneyFields()}
  $('#btnSalvarCfg').onclick=()=>{cfg={...cfg,prof:n($('#cfgProf').value),ajud:n($('#cfgAjud').value),almoco:n($('#cfgAlmoco').value),almoco_mode:$('#cfgAlmocoMode').value,mult_sab:n($('#cfgMultSab').value)||1.5,mult_dom:n($('#cfgMultDom').value)||2};persist();renderAll();toast('Configurações salvas')};

  $('#btnFiltrar').onclick=renderAll;$('#btnLimpar').onclick=()=>{$('#fDe').value='';$('#fAte').value='';$('#fFornecedor').value='';$('#selOF').value='__ALL__';renderAll()};$('#selOF').onchange=renderAll;
  $('#btnExportPDF').onclick=()=>window.print();
  const CSV_HEAD=['of_id','data','fornecedor','materiais','profissionais','ajudantes','almoco','translado','tipo_dia'];
  $('#btnExportar').onclick=()=>{const rows=[CSV_HEAD,...lanc.map(l=>CSV_HEAD.map(k=>l[k]??''))],csv=rows.map(r=>r.map(v=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='adequacoes_civis_lancamentos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  const splitCsv=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out.map(x=>x.trim())};
  $('#inputCSV').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const lines=(await f.text()).replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').filter(Boolean),head=splitCsv(lines.shift()||'');if(!CSV_HEAD.every(h=>head.includes(h)))throw new Error('Cabeçalho inválido');const idx=Object.fromEntries(CSV_HEAD.map(h=>[h,head.indexOf(h)]));lanc=lines.map(line=>{const c=splitCsv(line),g=k=>c[idx[k]]??'';return{id:uid(),of_id:g('of_id'),data:g('data'),fornecedor:canonicalSupplierName(g('fornecedor')),materiais:n(g('materiais')),profissionais:parseInt(g('profissionais'))||0,ajudantes:parseInt(g('ajudantes'))||0,almoco:n(g('almoco')),translado:n(g('translado')),tipo_dia:g('tipo_dia')||'util'}});persist();renderAll();toast('CSV importado')}catch(err){alert(`Não foi possível importar: ${err.message}`)}e.target.value=''};

  moneyFields();fillOFs(false);renderDatalist();renderAll();renderOFs();renderSuppliers();
});
