'use strict';
(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(num(v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const parse=(s,f)=>{try{return s?JSON.parse(s):structuredClone(f)}catch{return structuredClone(f)}};
  const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)};

  const KEY_M='multprest_prices_materials_v1', KEY_Q='multprest_prices_quantities_v1', KEY_B='multprest_prices_budgets_v1';
  const ORC_MATS='multprest_orc_bdi_materials_v1';
  const CLIENTS=[['brf','BRF'],['couros','JBS Couros'],['0%','inss0'],['jbs','JBS'],['vibra','VIBRA'],['agrogen','Agrogen'],['migplus','MIG PLUS'],['sbe','LAR']];
  let materials=parse(localStorage.getItem(KEY_M),[]), quantities=parse(localStorage.getItem(KEY_Q),{}), budgets=parse(localStorage.getItem(KEY_B),[]);
  if(!Array.isArray(materials))materials=[]; if(!Array.isArray(budgets))budgets=[];
  let editing=null, sending=null;
  const save=()=>{localStorage.setItem(KEY_M,JSON.stringify(materials));localStorage.setItem(KEY_Q,JSON.stringify(quantities));localStorage.setItem(KEY_B,JSON.stringify(budgets))};
  const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const norm=s=>String(s||'').trim();
  const catName=m=>norm(m.category), subName=m=>norm(m.subcategory);
  const cats=()=>[...new Set(materials.map(catName).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const subs=c=>[...new Set(materials.filter(m=>!c||catName(m)===c).map(subName).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));

  function filtered(){const q=norm($('#searchMaterial').value).toLowerCase(),s=norm($('#searchSupplier').value).toLowerCase(),c=$('#filterCategory').value,sc=$('#filterSubcategory').value;return materials.filter(m=>(!q||norm(m.name).toLowerCase().includes(q))&&(!s||norm(m.supplier).toLowerCase().includes(s))&&(!c||catName(m)===c)&&(!sc||subName(m)===sc))}
  function grand(list=filtered()){return list.reduce((a,m)=>a+num(m.price)*num(quantities[m.id]),0)}
  function renderFilters(){
    const c=$('#filterCategory').value, sc=$('#filterSubcategory').value;
    $('#filterCategory').innerHTML='<option value="">Todas as categorias</option>'+cats().map(x=>`<option ${x===c?'selected':''}>${esc(x)}</option>`).join('');
    const arr=subs(c);$('#filterSubcategory').disabled=!c;$('#filterSubcategory').innerHTML='<option value="">Todas as subcategorias</option>'+arr.map(x=>`<option ${x===sc?'selected':''}>${esc(x)}</option>`).join('');
    $('#categoryList').innerHTML=cats().map(x=>`<option value="${esc(x)}"></option>`).join('');$('#subcategoryList').innerHTML=subs('').map(x=>`<option value="${esc(x)}"></option>`).join('');
    const chips=[];if($('#searchMaterial').value)chips.push(['Busca: '+$('#searchMaterial').value,'searchMaterial']);if($('#searchSupplier').value)chips.push(['Fornecedor: '+$('#searchSupplier').value,'searchSupplier']);if(c)chips.push([c,'filterCategory']);if(sc)chips.push([sc,'filterSubcategory']);$('#activeFilters').innerHTML=chips.map(([t,k])=>`<button class="chip" data-clear="${k}">${esc(t)} ×</button>`).join('');$$('[data-clear]').forEach(b=>b.onclick=()=>{const el=$('#'+b.dataset.clear);el.value='';if(b.dataset.clear==='filterCategory')$('#filterSubcategory').value='';renderAll()});
  }
  function renderTable(){const list=filtered();$('#statCount').textContent=list.length;$('#visibleCount').textContent=`${list.length} exibidos`;$('#statTotal').textContent=money(grand(list));$('#emptyState').classList.toggle('hidden',list.length>0);$('#materialsBody').innerHTML=list.map(m=>`<tr data-id="${m.id}"><td><div class="mat-name">${esc(m.name)}</div></td><td>${catName(m)?esc(catName(m)):'<span class="muted">-</span>'}</td><td><span class="muted">${subName(m)?esc(subName(m)):'-'}</span></td><td><span class="muted">${esc(m.supplier||'-')}</span></td><td>${esc(m.unit||'-')}</td><td class="price">${money(m.price)}</td><td><input class="qty" type="number" min="0" step="0.01" value="${num(quantities[m.id])||''}" placeholder="0"></td><td class="row-total">${num(quantities[m.id])?money(num(m.price)*num(quantities[m.id])):'-'}</td><td><div class="row-actions"><button class="action send">＋ Orçamento</button><button class="action edit">Editar</button><button class="action del">Excluir</button></div></td></tr>`).join('');
    $$('#materialsBody tr').forEach(r=>{const m=materials.find(x=>x.id===r.dataset.id);r.querySelector('.qty').oninput=e=>{quantities[m.id]=num(e.target.value);save();renderTable()};r.querySelector('.edit').onclick=()=>openEditor(m);r.querySelector('.del').onclick=()=>delMaterial(m);r.querySelector('.send').onclick=()=>openSend(m)});
  }
  function renderAll(){renderFilters();renderTable()}

  function openEditor(m=null){editing=m?.id||null;$('#editorTitle').textContent=m?'Editar Material':'Novo Material';$('#edName').value=m?.name||'';$('#edUnit').value=m?.unit||'';$('#edPrice').value=m?.price||'';$('#edSupplier').value=m?.supplier||'';$('#edCategory').value=m?.category||'';$('#edSubcategory').value=m?.subcategory||'';$('#editor').classList.remove('hidden');$('#edName').focus()}
  function closeEditor(){$('#editor').classList.add('hidden');editing=null}
  function saveMaterial(){const name=norm($('#edName').value),unit=norm($('#edUnit').value),price=num($('#edPrice').value);if(!name||!unit||price<=0){alert('Preencha Material, Unidade e um Preço maior que zero.');return}const data={name,unit,price,supplier:norm($('#edSupplier').value),category:norm($('#edCategory').value),subcategory:norm($('#edSubcategory').value),updatedAt:new Date().toISOString()};if(editing){const i=materials.findIndex(x=>x.id===editing);materials[i]={...materials[i],...data}}else materials.push({id:id(),...data,createdAt:new Date().toISOString()});save();closeEditor();renderAll();toast('Material salvo')}
  function delMaterial(m){if(!confirm(`Excluir “${m.name}”?`))return;materials=materials.filter(x=>x.id!==m.id);delete quantities[m.id];save();renderAll()}

  function openModal(x){$('#'+x).classList.remove('hidden')} function closeModal(x){$('#'+x).classList.add('hidden')}
  function saveBudget(){const name=norm($('#budgetName').value);const items=materials.filter(m=>num(quantities[m.id])>0).map(m=>({materialId:m.id,quantity:num(quantities[m.id]),priceSnapshot:num(m.price),nameSnapshot:m.name,unitSnapshot:m.unit}));if(!name){alert('Digite um nome para o orçamento.');return}if(!items.length){alert('Adicione quantidades aos materiais antes de salvar.');return}budgets.unshift({id:id(),name,createdAt:new Date().toISOString(),items});save();$('#budgetName').value='';closeModal('budgetSaveModal');renderBudgets();toast('Orçamento salvo')}
  function renderBudgets(){if(!budgets.length){$('#budgetsList').innerHTML='<div class="empty">Nenhum orçamento salvo ainda.</div>';return}$('#budgetsList').innerHTML=budgets.map(b=>`<div class="budget-row" data-id="${b.id}"><div><h3>${esc(b.name)}</h3><p>${new Date(b.createdAt).toLocaleString('pt-BR')} • ${b.items.length} item(ns)</p></div><div class="budget-buttons"><button class="btn blue load">Carregar</button><button class="btn red delete">Excluir</button></div></div>`).join('');$$('.budget-row').forEach(r=>{const b=budgets.find(x=>x.id===r.dataset.id);r.querySelector('.load').onclick=()=>{quantities={};b.items.forEach(i=>quantities[i.materialId]=num(i.quantity));save();closeModal('budgetsModal');renderAll();toast(`Orçamento “${b.name}” carregado`)};r.querySelector('.delete').onclick=()=>{if(confirm(`Excluir orçamento “${b.name}”?`)){budgets=budgets.filter(x=>x.id!==b.id);save();renderBudgets()}}})}

  function openSend(m){sending=m;$('#sendMaterialInfo').innerHTML=`<strong>${esc(m.name)}</strong><span>${esc(m.unit)} • ${money(m.price)}${m.supplier?` • ${esc(m.supplier)}`:''}</span>`;$('#sendQty').value=num(quantities[m.id])||1;$('#sendClient').innerHTML='<option value="">Selecione o cliente</option>'+CLIENTS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('');$('#sendClient').value='';updateSendTotal();openModal('sendModal')}
  function updateSendTotal(){if(sending)$('#sendTotal').textContent=money(num(sending.price)*num($('#sendQty').value))}
  function sendToBudget(){if(!sending)return;const qty=num($('#sendQty').value),clientId=$('#sendClient').value;if(qty<=0){alert('Informe uma quantidade maior que zero.');return}if(!clientId){alert('Selecione o cliente para aplicar o perfil BDI correto no Orçamento.');return}const list=parse(localStorage.getItem(ORC_MATS),[]);const items=Array.isArray(list)?list:[];items.push({id:id(),clientId,description:sending.name,valorMaterial:num(sending.price)*qty,source:'tabela-precos',sourceMaterialId:sending.id,unit:sending.unit,sourceUnitPrice:num(sending.price),quantity:qty,supplier:sending.supplier||'',category:sending.category||'',subcategory:sending.subcategory||'',sourceDate:new Date().toISOString()});localStorage.setItem(ORC_MATS,JSON.stringify(items));closeModal('sendModal');toast('Material adicionado ao Orçamento');sending=null}

  async function importFile(file){try{let rows=[];const ext=file.name.split('.').pop().toLowerCase();if(ext==='json'){const j=JSON.parse(await file.text());rows=Array.isArray(j)?j:(j.materials||[])}else if(ext==='csv'){rows=parseCSV(await file.text())}else{if(!window.XLSX)throw new Error('Biblioteca Excel indisponível');const data=await file.arrayBuffer(),wb=XLSX.read(data),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''})}let count=0;for(const r of rows){const get=(...keys)=>{for(const k of keys){if(r[k]!==undefined&&r[k]!==null&&String(r[k]).trim()!=='')return r[k]}return''};const name=norm(get('Material','material','name','Nome','Nome do Material')),unit=norm(get('Unidade','unidade','unit','UND','Und')),rawPrice=get('Preço','Preco','preço','price','Preço Unitário','PREÇO UNIT. REF. (R$)'),price=typeof rawPrice==='number'?rawPrice:num(String(rawPrice).includes(',')?String(rawPrice).replace(/\./g,'').replace(',','.'):String(rawPrice));if(!name||!unit||price<=0)continue;materials.push({id:id(),name,unit,price,supplier:norm(get('Fornecedor','fornecedor','supplier')),category:norm(get('Categoria','categoria','category')).replace(/^\S+\s+/u,x=>/[\p{Extended_Pictographic}]/u.test(x)?'':x),subcategory:norm(get('Subcategoria','subcategoria','subcategory')),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});count++}save();renderAll();toast(`${count} materiais importados`)}catch(e){console.error(e);alert('Não foi possível importar o arquivo. Confira as colunas e o formato.')}}
  function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=lines[0].includes(';')?';':',';const head=lines[0].split(sep).map(x=>x.replace(/^"|"$/g,'').trim());return lines.slice(1).map(line=>{const vals=line.split(sep).map(x=>x.replace(/^"|"$/g,'').trim());return Object.fromEntries(head.map((h,i)=>[h,vals[i]??'']))})}
  function exportExcel(){const rows=materials.map(m=>({Material:m.name,Fornecedor:m.supplier||'',Unidade:m.unit,'Preço':num(m.price),Categoria:m.category||'',Subcategoria:m.subcategory||''}));if(window.XLSX){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Materiais');XLSX.writeFile(wb,`tabela-precos-${new Date().toLocaleDateString('pt-BR').replace(/\//g,'-')}.xlsx`)}else{const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tabela-precos.json';a.click();URL.revokeObjectURL(a.href)}}

  $('#btnAdd').onclick=()=>openEditor();$('#btnCancelEditor').onclick=closeEditor;$('#btnCancelEditor2').onclick=closeEditor;$('#btnSaveMaterial').onclick=saveMaterial;
  ['searchMaterial','searchSupplier'].forEach(x=>$('#'+x).oninput=renderAll);$('#filterCategory').onchange=()=>{$('#filterSubcategory').value='';renderAll()};$('#filterSubcategory').onchange=renderAll;
  $('#btnSaveBudget').onclick=()=>openModal('budgetSaveModal');$('#btnConfirmSaveBudget').onclick=saveBudget;$('#btnBudgets').onclick=()=>{renderBudgets();openModal('budgetsModal')};
  $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#sendQty').oninput=updateSendTotal;$('#btnConfirmSend').onclick=sendToBudget;
  $('#btnImport').onclick=()=>$('#fileImport').click();$('#fileImport').onchange=e=>{const f=e.target.files?.[0];if(f)importFile(f);e.target.value=''};$('#btnExport').onclick=exportExcel;
  $('#btnDeleteAll').onclick=()=>{if(!confirm('ATENÇÃO: isso apagará TODOS os materiais desta Tabela de Preços neste navegador. Continuar?'))return;if(!confirm('Esta ação não pode ser desfeita. Confirmar?'))return;materials=[];quantities={};save();renderAll();toast('Materiais apagados')};
  $$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
  renderAll();
})();