'use strict';
(() => {
  const C=window.CalcHHCore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),moeda=n=>brl.format(Number.isFinite(n)?n:0),num=v=>Number.isFinite(Number(v))?Number(v):0;
  let cargoAtivo=null;
  const toast=msg=>{const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)};
  const row=(l,v,c='')=>`<div class="result-row ${c}"><span>${l}</span><strong>${moeda(v)}</strong></div>`;
  const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function inputs(){$$('[data-field]').forEach(e=>e.value=C.dados[e.dataset.field])}
  function cargos(){
    $('#cargoList').innerHTML=C.cargos.map(c=>`<button class="cargo-btn ${cargoAtivo===c.id?'active':''}" data-cargo="${c.id}">${c.nome}<small>${moeda(c.salarioBase)}</small></button>`).join('');
    $('#btnLimparCargo').classList.toggle('hidden',!cargoAtivo);$('#cargoNote').classList.toggle('hidden',!cargoAtivo);
    $$('.cargo-btn').forEach(b=>b.onclick=()=>{const c=C.cargos.find(x=>x.id===b.dataset.cargo);if(!c)return;cargoAtivo=c.id;C.dados={...C.dados,salario:c.salarioBase,insalubridadePerc:20};C.saveDados();renderAll()});
  }
  function results(){
    const d=C.dados,r=C.calcular();
    $('#seguroRateio').textContent=`Rateado por ${d.qtdFunc} funcionário${d.qtdFunc!==1?'s':''}: ${moeda(r.seguroVidaFunc)}/func`;
    $('#margemAntecipacao').textContent=`${r.margemAntecipacaoCalculada.toFixed(1)}%`;$('#margemNegociacaoValor').textContent=moeda(r.margemNegociacaoValor);$('#precoComMargemMini').textContent=moeda(r.precoComMargem);$('#valorHoraMargemMini').textContent=moeda(r.valorHoraComMargem);
    $('#encargosResults').innerHTML=[row('Base de Encargos',r.baseEncargos,'sub'),row('Férias (1/12)',r.ferias),row('1/3 Constitucional',r.tercoFerias),row('Férias + 1/3',r.feriasComTerco,'sub'),row('13º Salário',r.decimoTerceiro),row('FGTS Base (8%)',r.fgtsBase),row('FGTS Férias',r.fgtsFerias),row('FGTS 13º',r.fgts13),row('FGTS Total',r.fgtsTotal,'sub'),row(`INSS Base (${d.inssPatronalPerc}%)`,r.inssBase),row('INSS Férias',r.inssFerias),row('INSS 13º',r.inss13),row('INSS Patronal Total',r.inssPatronal,'sub'),row('Provisão Rescisão',r.provisaoRescisao),row('Total Encargos',r.encargosTotais,'em')].join('');
    $('#percentualEncargos').textContent=`${r.percentualEncargos.toFixed(1)}% sobre a base de encargos`;
    $('#custosResults').innerHTML=[row('Custos Fixos Individuais',r.custosFixosIndividuais),row('Custo Operacional/Func',r.custoOperFunc),row('Seguro de Vida/Func',r.seguroVidaFunc),row('Treinamentos NR/Mês',r.treinamentosMensal)].join('');
    $('#finalResults').innerHTML=[row('Custo Total Mensal',r.custoTotalMensal,'sub'),row('Preço Final',r.precoFinal,'em')].join('');
    $('#offerBox').innerHTML=d.descontoNegociacaoPerc>0?`<div><span>Preço p/ Oferecer (+${d.descontoNegociacaoPerc}%)</span><strong>${moeda(r.precoComMargem)}</strong></div><small>Margem: ${moeda(r.margemNegociacaoValor)}</small>`:'';
    $('#jornadaLabel').textContent=d.jornada;const mao=d.jornada?(r.baseEncargos+r.encargosTotais)/d.jornada:0,fix=d.jornada?r.custosFixosIndividuais/d.jornada:0,op=d.jornada?(r.custoOperFunc+r.seguroVidaFunc+r.treinamentosMensal)/d.jornada:0,il=Math.max(0,r.valorHora-mao-fix-op);
    $('#compositionGrid').innerHTML=[['Mão de Obra','Salário + prêmio + insalubridade + encargos',mao],['Custos Fixos','Alimentação, EPI, transporte, exames, plano saúde',fix],['Operacional','Rateio operacional + seguro + treinamentos',op],['Impostos + Lucro','Formação do preço até a hora final',il]].map(x=>`<div class="composition-item"><span>${x[0]}</span><small>${x[1]}</small><strong>${moeda(x[2])}</strong></div>`).join('');
    $('#valorHoraBig').textContent=moeda(r.valorHora);$('#valorHoraAntecipacaoBig').textContent=`Com antecipação: ${moeda(r.valorHoraComAntecipacao)}`;$('#valorHoraMargemBig').textContent=moeda(r.valorHoraComMargem);
    $('#reversoResults').innerHTML=[row('Preço considerado',r.reverso.precoFinal,'em'),row('INSS retido',-r.reverso.inssRetido),row('Simples',-r.reverso.simples),row('ISSQN',-r.reverso.issqn),row('Total impostos',-r.reverso.totalImpostos),row('Antecipação',-r.reverso.custoAntecipacao),row('Receita líquida',r.reverso.receitaLiquida,'sub'),row('Custo total mensal',-r.reverso.custoTotalMensal),row(`Lucro real (${r.reverso.lucroRealPerc.toFixed(1)}%)`,r.reverso.lucroReal,'em')].join('');
    const ps=$('#proofStatus');ps.className=`proof-status ${r.reverso.confere?'ok':'bad'}`;ps.textContent=r.reverso.confere?`✓ Confere com lucro esperado de ${d.lucroPerc}%`:`Atenção: diferença para lucro esperado ${moeda(r.reverso.diferenca)}`;
    $('#reversoMargemResults').innerHTML=[row('Preço com margem',r.reversoComMargem.precoComMargem,'em'),row('Total impostos',-r.reversoComMargem.totalImpostos),row('Antecipação',-r.reversoComMargem.custoAntecipacao),row('Receita líquida',r.reversoComMargem.receitaLiquida,'sub'),row(`Lucro real (${r.reversoComMargem.lucroRealPerc.toFixed(1)}%)`,r.reversoComMargem.lucroReal,'em'),row('Ganho extra',r.reversoComMargem.ganhoExtra,'em')].join('');
  }
  function empresaTable(){let h='<thead><tr><th>Cargo</th>'+C.EMPRESAS.map(e=>`<th>${e.nome}<span class="company-days">${e.diasAntecipacao} dias</span></th>`).join('')+'</tr></thead><tbody>';h+=C.cargos.map(c=>`<tr><td>${c.nome}</td>${C.EMPRESAS.map(e=>`<td class="value">${moeda(C.calcularValorHoraTabela(c.salarioBase,e.diasAntecipacao))}</td>`).join('')}</tr>`).join('');$('#empresaTable').innerHTML=h+'</tbody>'}
  function costTotals(){const t=C.custosFixos.reduce((s,i)=>s+num(i.valor),0),p=C.dados.qtdFunc>0?t/C.dados.qtdFunc:0;$('#totalCustoFixo').textContent=moeda(t);$('#custoFixoFunc').textContent=moeda(p);$('#custoFixoFuncLabel').textContent=`Total ÷ ${C.dados.qtdFunc} funcionários (da aba Calculadora)`}
  function costs(){
    $('#custosFixosList').innerHTML=C.custosFixos.map(i=>`<div class="cost-row" data-id="${i.id}"><input class="cost-name" value="${esc(i.nome)}"><input class="cost-value" type="number" step="0.01" value="${i.valor}"><button class="remove-btn" title="Remover">×</button></div>`).join('');
    $$('.cost-row').forEach(e=>{const i=C.custosFixos.find(x=>x.id===e.dataset.id);e.querySelector('.cost-name').oninput=v=>{i.nome=v.target.value;C.saveCustos()};e.querySelector('.cost-value').oninput=v=>{i.valor=num(v.target.value);C.saveCustos();costTotals()};e.querySelector('.remove-btn').onclick=()=>{C.custosFixos=C.custosFixos.filter(x=>x.id!==i.id);C.saveCustos();costs()}});costTotals();
  }
  function renderAll(){inputs();cargos();results();empresaTable();costTotals()}
  $$('[data-field]').forEach(e=>e.addEventListener('input',()=>{C.dados={...C.dados,[e.dataset.field]:num(e.value)};if(e.dataset.field==='salario'&&cargoAtivo){const c=C.cargos.find(x=>x.id===cargoAtivo);if(c){c.salarioBase=C.dados.salario;C.saveCargos()}}C.saveDados();results();cargos();empresaTable();costTotals()}));
  $$('.tab-btn').forEach(b=>b.onclick=()=>{$$('.tab-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${b.dataset.tab}`))});
  $('#btnLimparCargo').onclick=()=>{cargoAtivo=null;C.dados={...C.DEFAULT_DADOS};C.saveDados();renderAll()};$('#btnReset').onclick=()=>{if(confirm('Resetar os valores da calculadora para os padrões do sistema?')){C.dados={...C.DEFAULT_DADOS};cargoAtivo=null;C.saveDados();renderAll();toast('Calculadora resetada')}};
  $('#btnSalvarBasico').onclick=()=>{C.saveDados();toast('Valores salvos neste navegador')};$('#btnSalvarOperacional').onclick=()=>{C.saveDados();toast('Custos operacionais salvos neste navegador')};
  $('#btnAddCusto').onclick=()=>{C.custosFixos.push({id:String(Date.now()),nome:'',valor:0});C.saveCustos();costs()};$('#btnResetCustos').onclick=()=>{if(confirm('Restaurar a lista original de custos fixos?')){C.custosFixos=C.clone(C.CUSTOS_FIXOS_DEFAULT);C.saveCustos();costs()}};
  const download=(name,text,type='text/plain;charset=utf-8')=>{const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  $('#btnExportTxt').onclick=()=>{const d=C.dados,r=C.calcular();download('calculadora-hh.txt',`CALCULADORA HH - CUSTO DE FUNCIONÁRIO\n=====================================\n\nSalário Base: ${moeda(d.salario)}\nJornada Mensal: ${d.jornada} horas\nPrêmio Assiduidade: ${moeda(d.premioAssiduidade)}\nInsalubridade: ${d.insalubridadePerc}%\nBase de Encargos: ${moeda(r.baseEncargos)}\nTotal Encargos: ${moeda(r.encargosTotais)}\nCusto Total Mensal: ${moeda(r.custoTotalMensal)}\nPreço Final: ${moeda(r.precoFinal)}\nValor Hora: ${moeda(r.valorHora)}\nValor Hora c/ Antecipação: ${moeda(r.valorHoraComAntecipacao)}\nValor Hora c/ Margem: ${moeda(r.valorHoraComMargem)}\n`)};
  $('#btnExportCsv').onclick=()=>{const d=C.dados,r=C.calcular(),rows=[['Campo','Valor'],['Salário Base',d.salario],['Jornada Mensal',d.jornada],['Prêmio Assiduidade',d.premioAssiduidade],['Insalubridade (%)',d.insalubridadePerc],['Base de Encargos',r.baseEncargos],['Total Encargos',r.encargosTotais],['Custo Total Mensal',r.custoTotalMensal],['Preço Final',r.precoFinal],['Valor Hora',r.valorHora],['Valor Hora c/ Antecipação',r.valorHoraComAntecipacao],['Valor Hora c/ Margem',r.valorHoraComMargem]];download('calculadora-hh.csv',rows.map(x=>x.join(';')).join('\n'),'text/csv;charset=utf-8')};
  costs();renderAll();
})();